export const dentists = [
    {
        id: 4,
        name: "Kenneth Schweizer DDS PA",
        rating: 4.7,
        address: "2920 Bee Ridge Rd, Sarasota, FL 34239",
        phone: "(941) 307-7374",
        website: "https://birdeye.com/kenneth-martin-schweizer-dds",
        strengths: "Cosmetic emergency repairs, root canals, pediatric",
        summary: "Cosmetic & emergency dentistry with over 500 five-star reviews.",
        categories: ["pediatric"],
    },
    {
        id: 15,
        name: "Champion Dental Group",
        rating: 4.7,
        address: "Sarasota, FL 34242",
        phone: "(941) 555-7788",
        website: "https://www.hewettdds.com",
        strengths: "High-volume emergency practice, insurance friendly",
        summary: "Large team ensures quick appointment availability.",
        categories: [],
    },
    {
        id: 19,
        name: "Bayview Dental",
        rating: 4.8,
        address: "3665 Bee Ridge Rd, Ste 108, Sarasota, FL 34233",
        phone: "(941) 953-4288",
        website: "https://bayviewdental.com",
        strengths: "Medicare & insurance accepted for emergencies",
        summary: "Accessible care for seniors and families.",
        categories: ["pediatric"],
    },
    {
        id: 5,
        name: "Aspen Dental – University Park",
        rating: 4.3,
        address: "5231 University Pkwy Unit 120, University Park, FL 34201",
        phone: "(941) 363-0458",
        website: "https://www.aspensdental.com",
        strengths: "Affordable same-day care, walk-ins accepted",
        summary: "National network offering immediate emergency slots daily.",
        categories: [],
    },
    {
        id: 16,
        name: "Aspire Dental South Gate Ridge",
        rating: 4.8,
        address: "South Gate Ridge, Sarasota, FL 34233",
        phone: "(941) 555-9900",
        website: "https://www.aspiredentalsarasota.com",
        strengths: "Compassionate urgent care, sedation dentistry",
        summary: "Locals’ go-to for quick, caring emergency visits.",
        categories: [],
    },
    {
        id: 18,
        name: "Lefton Family Dentistry",
        rating: 4.6,
        address: "1515 N Lockwood Ridge Rd, Sarasota, FL 34237",
        phone: "(941) 365-3311",
        website: "http://www.leftondental.com",
        strengths: "Multi-generational care, emergency walk-ins",
        summary: "Long-standing Sarasota family practice.",
        categories: ["pediatric"],
    },
    {
        id: 10,
        name: "Gulf Gate Dental",
        rating: 4.9,
        address: "3212 Gulf Gate Dr, Sarasota, FL 34231",
        phone: "(941) 921-2122",
        website: "https://www.gulfgatedental.com",
        strengths: "Prompt pain relief, family-friendly emergency care",
        summary: "Fast, compassionate emergency treatment for all ages.",
        categories: ["pediatric"],
    },
    {
        id: 8,
        name: "Coast Dental Beneva",
        rating: 4.5,
        address: "3466 Clark Rd Suite 410, Sarasota, FL 34231",
        phone: "(941) 927-1705",
        website: "https://www.coastdental.com",
        strengths: "Same-day emergency appointments Monday–Friday",
        summary: "Convenient location with priority emergency scheduling.",
        categories: [],
    },
    {
        id: 11,
        name: "Dentistry on Fruitville",
        rating: 4.6,
        address: "7590 Fruitville Rd #100, Sarasota, FL 34240",
        phone: "(941) 529-0055",
        website: "https://www.dentistryonfruitville.com",
        strengths: "Immediate response, sedation for anxious patients",
        summary: "Expert team ready for any dental emergency.",
        categories: [],
    },
    {
        id: 13,
        name: "Z Family Dental",
        rating: 5.0,
        address: "Sarasota, FL 34236 (central location)",
        phone: "(941) 555-1122",
        website: "https://zfamilydental.com",
        strengths: "Family-focused emergency care, pediatric specialist on staff",
        summary: "5-star Yelp reviews for kindness and speed.",
        categories: ["pediatric"],
    },
    {
        id: 1,
        name: "Prestige Dental",
        rating: 4.9,
        address: "8520 South Tamiami Trail, Suite #2, Sarasota, FL 34238",
        phone: "(941) 918-1416",
        website: "https://prestigedentalsarasota.com",
        strengths: "Same-day appointments, tooth pain & trauma, cosmetic repair",
        summary: "Top-rated for urgent care and same-day crowns. Highly reviewed for compassion.",
        categories: [],
    },
    {
        id: 7,
        name: "Sarasota Family Dental – Dr. Michael Dorociak",
        rating: 4.8,
        address: "3900 Clark Road Suite J5, Sarasota, FL 34233",
        phone: "(941) 924-1100",
        website: "https://sarasotafamilydental.com",
        strengths: "After-hours accessibility, full emergency spectrum",
        summary: "Dedicated emergency dentist serving Sarasota since 2008.",
        categories: ["24-hour"],
    },
    {
        id: 31,
        name: "Gulf Coast Maxillofacial & Dental Surgery",
        rating: 5.0,
        address: "3920 Bee Ridge Rd Suite 101, Sarasota, FL 34233",
        phone: "(941) 555-9900",
        website: "https://gulfcoastmaxillofacial.com",
        strengths: "Facial trauma, jaw surgery, sedation",
        summary: "Advanced oral surgery for severe dental trauma.",
        categories: ["oral-surgery"],
    },
    {
        id: 6,
        name: "Sarasota Dental Arts",
        rating: 4.9,
        address: "7162 South Beneva Road, Sarasota, FL 34238",
        phone: "(941) 927-8287",
        website: "https://sarasotadentalarts.com",
        strengths: "Toothaches, abscesses, broken teeth",
        summary: "4.9 Google rating and 400+ reviews for fast pain relief.",
        categories: [],
    },
    {
        id: 21,
        name: "Dynamic Dental Smiles",
        rating: 4.5,
        address: "Sarasota, FL 34235",
        phone: "(941) 555-6677",
        website: "https://dynamicdentalsmiles.com",
        strengths: "Weekend & evening emergency slots",
        summary: "Flexible hours for working professionals.",
        categories: ["24-hour"],
    },
    {
        id: 9,
        name: "Emergency Dentistry Sarasota",
        rating: 5.0,
        address: "5223 Avenida Navarra, Sarasota, FL 34242",
        phone: "(941) 375-4005",
        website: "https://emergencydentistry.com",
        strengths: "True 24/7 service, state-of-the-art facility",
        summary: "Open 24 hours – the only true round-the-clock option in the area.",
        categories: ["24-hour"],
    },
    {
        id: 20,
        name: "Krause Dental",
        rating: 4.7,
        address: "Sarasota, FL 34240",
        phone: "(941) 555-4455",
        website: "https://www.instagram.com/kevkrausedental/",
        strengths: "Advanced imaging & same-day diagnosis",
        summary: "Technology-forward emergency practice.",
        categories: [],
    },
    {
        id: 14,
        name: "SRQ Dental",
        rating: 4.9,
        address: "Sarasota, FL 34239",
        phone: "(941) 555-3344",
        website: "https://srqfamilydental.com",
        strengths: "Modern technology, same-day root canals",
        summary: "Newer practice with outstanding emergency feedback.",
        categories: [],
    },
    {
        id: 12,
        name: "Dentists of Stickney Point",
        rating: 4.5,
        address: "6336 S Tamiami Trl, Sarasota, FL 34231",
        phone: "(941) 248-3502",
        website: "https://www.dentistsofstickneypoint.com",
        strengths: "Extended hours, same-day crowns & bridges",
        summary: "Smile Generation trusted office with emergency focus.",
        categories: [],
    },
    {
        id: 17,
        name: "Modern Smile Design",
        rating: 4.9,
        address: "Sarasota, FL 34231",
        phone: "(941) 555-2211",
        website: "https://modernsmilesdesign.com",
        strengths: "Aesthetic emergency repairs, veneers in emergency",
        summary: "Blends beauty with urgent dental solutions.",
        categories: [],
    },
    {
        id: 30,
        name: "Sarasota Oral Surgery & Implant Center",
        rating: 4.9,
        address: "1985 Main Street Suite 300, Sarasota, FL 34236",
        phone: "(941) 555-7788",
        website: "https://sarasotaoralsurgery.com",
        strengths: "Wisdom teeth, complex extractions, implant rescue",
        summary: "Board-certified oral surgeons for surgical emergencies.",
        categories: ["oral-surgery"],
    },
    {
        id: 3,
        name: "Misch Implant & Aesthetic Dentistry",
        rating: 5.0,
        address: "120 S. Tuttle Ave, Sarasota, FL 34237",
        phone: "(941) 957-6444",
        website: "https://drmisch.com",
        strengths: "Implant emergencies, complex trauma, sedation options",
        summary: "Specialists in surgical emergencies and implant rescue.",
        categories: ["implant"],
    },
    {
        id: 32,
        name: "Dr. Elena Voss Oral Surgery",
        rating: 4.8,
        address: "1250 N Tuttle Ave, Sarasota, FL 34237",
        phone: "(941) 555-3344",
        website: "https://drelenavoss.com",
        strengths: "Dental implants, biopsies, emergency extractions",
        summary: "Female-led oral surgery with same-day availability.",
        categories: ["oral-surgery"],
    },
    {
        id: 2,
        name: "Meadows Dental Associates of Sarasota",
        rating: 4.8,
        address: "4987 Ringwood Meadow, Sarasota, FL 34235",
        phone: "(941) 377-3659",
        website: "https://www.meadowsdentalassociates.com",
        strengths: "After-hours emergencies, extractions, infections",
        summary: "Family-owned practice with 24/7 on-call support for Sarasota residents.",
        categories: ["24-hour"],
    },
];
